### ISSUE TITLE
If Hare receives a null payload over a rpc, connection drops

### ISSUE THREAD

**Issue by TechnotronicOz** [C2FO/hare#10]
Hare always expects an object in the payload, if you get `null`, it causes Hare to error out and drop the connection to the temp queue. We need to do a `if (msg && msg.error) {` to test `msg` and make sure it is not `null` or `undefined`. With that, Hare will log out a `TypeError` but not drop the connection.

**Comment by garrypolley** [comment]
It seems the code in question is here:

https://github.com/C2FO/hare/blob/master/lib/rpc.js#L49-L52

It seems like `null` is a valid response on a rabbit queue.

Current code:

```js
if (msg.error) {
     p.errback(new Error(msg.error));
   } else {
     p.callback(msg);
}
```

Should it simply pass the `null` or `undefined` message along? Rather than error?  Allow the callback to handle it? 

```js
if (msg && msg.error) {
     p.errback(new Error(msg.error));
   } else {
     p.callback(msg);
}
```

Is there an issue with passing `null` or `undefined` along to the callback?

**Comment by doug-martin** [comment]
@garrypolley no that is the solution that we tested this morning.

**Comment by doug-martin** [comment]
@garrypolley I mean yes that will work we just need to commit and publish it.

**Comment by TechnotronicOz** [comment]
Closed. See https://github.com/C2FO/hare/pull/11
